### ISSUE TITLE
Tag new version please, missing default option now

### ISSUE THREAD

**Issue by TomasVotruba** [lookyman/nette-proxy#3]
![image](https://cloud.githubusercontent.com/assets/924196/21321451/2f7b9cfe-c615-11e6-8b28-2ddd2e14a563.png)

https://github.com/lookyman/nette-proxy/compare/v1.0.0...master#diff-04c6e90faac2675aa89e2176d2eec7d8R30

**Comment by lookyman** [comment]
Version 1.1.0 has been tagged https://github.com/lookyman/nette-proxy/releases/tag/v1.1.0

**Comment by TomasVotruba** [comment]
Thank you!
